### PR TITLE
Fix titleization

### LINKED ISSUE #59: Titleize library does not work as needed
The titleize library does not work for stations we have already corrected. For example:
```
titleize('Foggy Bottom-GWU') = 'Foggy Bottom-Gwu'
```
Use a titleize function that will titleize user inputs that need titleization (i.e. takoma, silver spring) and not mess with station names that we've already corrected.

### PR DESCRIPTION
**Pull request by pmyers88**
Fixes #59

### CODE REVIEW

File: lib/utils.js [hunk 1]
```diff
@@ -85,16 +84,23 @@ exports.replaceAbbreviations = function (text, replacements) {
  * @return {object} WMATA train station
  */
 exports.findStationByName = function (stationName) {
-  return _.find(stations, ['Name', titleize(stationName)]);
+  return _.find(stations, ['Name', this.titleize(stationName)]);
 };
 
 /**
- * Returns the WMATA train station object with matching stationName from cached WMATA API
```
Comment (pmyers88) [inline lib/utils.js]: Due to a bad merge we had the findStationByName function twice in here.

File: test/test-utils.js [hunk 2]
```diff
@@ -120,29 +120,11 @@ test('test findStationByName for stations that exist and don\'t exist', function
   t.equal(typeof utils.findStationByName('not a real station name'), 'undefined', 'bad station name returns undefined');
 });
 
-test('test findStationByName for stations that exist and don\'t exist', function (t) {
```
Comment (pmyers88) [inline test/test-utils.js]: Remove duplicate `findByStationName` test.
