### PR TITLE
Fix Get Station Exception

### LINKED ISSUE #42: App throws "Unexpected exception TypeError: Cannot call method 'call' of undefined"
The exception is thrown for any `GetStation` request. Full info:

```
{
    "errorMessage": "Cannot call method 'call' of undefined",
    "errorType": "TypeError",
    "stackTrace": [
        "AlexaSkill.requestHandlers.IntentRequest (/var/task/vendor/AlexaSkill.js:32:37)",
        "AlexaSkill.execute (/var/task/vendor/AlexaSkill.js:110:24)",
        "exports.handler (/var/task/index.js:8:7)"
    ]
}
```

### PR DESCRIPTION
**Pull request by pmyers88**
Fixes #42

### CODE REVIEW

File: lib/metro-transit.js [hunk 1]
```diff
@@ -98,7 +96,7 @@ MetroTransit.prototype.intentHandlers = {
         response.tell(props.serviceAdvisoriesErrorSpeechOutput);
         return;
       }
-      var incidentList = _.pluck(incidents, 'Description');
```
Comment (pmyers88) [inline lib/metro-transit.js]: See [here](https://github.com/lodash/lodash/wiki/Changelog#v400).

File: lib/metro-transit.js [hunk 2]
```diff
@@ -16,23 +16,21 @@ var MetroTransit = function () {
 MetroTransit.prototype = Object.create(AlexaSkill.prototype);
 MetroTransit.prototype.constructor = MetroTransit;
 
-MetroTransit.prototype.eventHandlers = {
-  onSessionStarted: function (sessionStartedRequest, session) {
-    console.log('MetroTransit onSessionStarted requestId: ' + sessionStartedRequest.requestId +
-        ', sessionId: ' + session.sessionId);
-    // any initialization logic goes here
-  },
+MetroTransit.prototype.eventHandlers.onSessionStarted = function (sessionStartedRequest, session) {
```
Comment (r33beers) [inline lib/metro-transit.js]: How does changing this to this format fix the issue?

File: lib/metro-transit.js (hunk 1 above)
Comment (r33beers) [inline lib/metro-transit.js]: Whoops. I'm pretty sure I knew I needed to change this, but must have missed it in my commit.

File: lib/metro-transit.js (hunk 2 above)
Comment (pmyers88) [inline lib/metro-transit.js]: This is why I said I don't understand Javascript ;)

File: lib/metro-transit.js [hunk 3]
```diff
@@ -16,23 +16,21 @@ var MetroTransit = function () {
 MetroTransit.prototype = Object.create(AlexaSkill.prototype);
 MetroTransit.prototype.constructor = MetroTransit;
```
Comment (r33beers) [inline lib/metro-transit.js]: Let me try and run the debugger on what `MetroTransit.prototype.eventHandlers` is at this point. I bet there is more to this object and we were overwriting it.

Comment (pmyers88) [inline lib/metro-transit.js]: I'm doing it the same way as in the [sample project](https://github.com/amzn/alexa-skills-kit-js/blob/master/samples/helloWorld/src/index.js#L42).

File: lib/metro-transit.js (hunk 2 above)
Comment (pmyers88) [inline lib/metro-transit.js]: I tried changing it to this format because I looked at the diff and noticed we were using this format in October when it worked. It's also the same format as in the sample projects.

Comment (r33beers) [inline lib/metro-transit.js]: The difference is very clear in the debugger. Now, I want to understand why setting the value of `MetroTransit.prototype.eventHandlers` sets it where you would assume it sets it, but setting `MetroTransit.prototype.eventHandlers.onLaunch` sets it at the `AlexaSkill.prototype.eventHandlers.onLaunch` level.

Comment (r33beers) [inline lib/metro-transit.js]: Oh, I am way over thinking it. It is probably just because we didn't specify what `onIntent` was after we overrode the eventHandlers object. Let me give that a shot. It is probably better to override individual methods anyway (to avoid things like this happening), so we should merge this.

**Comment by r33beers** [comment]
@pmyers88 I pushed a commit to this branch with tests. I think that test commit highlights the difference between this branch and Master. On master, that test plan will fail, because `onIntent` does not exist. I believe this is all stemming from:
```
    IntentRequest: function (event, context, response) {
        this.eventHandlers.onIntent.call(this, event.request, event.session, response);
    },
```
and we overrode eventHandlers, so onIntent doesn't exists, therefore #42

File: lib/metro-transit.js (hunk 2 above)
Comment (pmyers88) [inline lib/metro-transit.js]: Oh, makes sense. Thanks for figuring this out.
